### ISSUE TITLE
SSL Certifications Verification Error

### ISSUE THREAD

**Issue by mgeeky** [MythicAgents/tetanus#6]
Hi!

While trying to launch the generated artifact executable on a linux running inside of a corporate network, it will fail due to SSL certificates being verified before accepting handshake:

```
thread 'main' panicked at 'called Result::unwrap() on an Err value: IoError(Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: UnknownIssuer") })', src/profiles/mod.rs:117:49
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

Please introduce an option to disable certificates verification.

Regards,
Mariusz.

**Comment by MEhrn00** [comment]
Hello!

Unfortunately the HTTP library I am using does not support using self-signed SSL certificates. I am in the process of migrating it over to a different HTTP library since it has caused issues with domain fronting. I can also include a build option to disable certificate validation once the migration is finished.
